### ISSUE TITLE
Persian numbers in codes

### ISSUE THREAD

**Issue by b-simjoo** [pcworms/template#2]
WPShamsi plugin changes all numbers (digits) to Persian.

**Comment by b-simjoo** [comment]
I don't know is it a good idea to fix this bug from our theme? I did a pull request many months ago but they didn't merge it so we have two options left:
1. Fork WPShamsi repository and fix it our self
2. Just edit installed plugin on our site
3. The bad idea: Call `wp_dequeue_script` to disable WPShamsi front-end script and enqueue our script.

**Comment by farooqkz** [comment]
I vote for the first option.

**Comment by b-simjoo** [comment]
OK, so I think we're done here.
