### ISSUE TITLE
Separating the frontend part from the backend part?

### ISSUE THREAD

**Issue by farooqkz** [pcworms/template#4]
From what I understand now, if one wants to make changes to this template, they have to learn PHP and WP specific functions/classes, too. If we could separate the frontend part from the backend one, one who wants to contribute to frontend won't have to know PHP and WP. Not sure if it's possible or that it's a good idea.

Perhaps one approach is a SPA with WP's RESTful API.

**Comment by b-simjoo** [comment]
I don't think that it is a good idea.
1. In my opinion, this is a big and fundamental change and it is better not to be related to the current template, it can be a fork of this, but it will be completely different from the current one.
2. In my opinion, it makes the template heavy and slow on the user's side. Our server has more resources than a mobile phone and WordPress is well-optimized for such purposes.
3. I think learning PHP will be fun for you!
4. I think we will have big problems with plugins.
