### ISSUE TITLE
use matomo insights (upper 5-min) to suggest posts in header box

### ISSUE THREAD

**Issue by b-simjoo** [pcworms/template#6]
We can randomly select 5 articles from the top 10 articles with the statistics of _5 minutes of user stoppage_ which are not even on the first page and display them in the header box.

_Extra Idea: we can also show 2 more random posts or posts with lower 5 minutes target. (Comment on this)_

**Comment by farooqkz** [comment]
I vote for exactly one random post from the lower section.

**Comment by b-simjoo** [comment]
Problem, how can I get matomo data in my development environment. Do you have any idea?!

**Comment by farooqkz** [comment]
Gather a dump of matomo DB, set up a local DB and use it.
